"""empty message

Revision ID: 1d7d56f9be79
Revises: c6aeda8efe88
Create Date: 2019-11-20 22:03:48.145836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7d56f9be79'
down_revision = 'c6aeda8efe88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('curso', sa.String(), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('disciplina_1', sa.String(), nullable=True),
    sa.Column('nota_d1', sa.Integer(), nullable=True),
    sa.Column('disciplina_2', sa.String(), nullable=True),
    sa.Column('nota_d2', sa.Integer(), nullable=True),
    sa.Column('disciplina_3', sa.String(), nullable=True),
    sa.Column('nota_d3', sa.Integer(), nullable=True),
    sa.Column('disciplina_4', sa.String(), nullable=True),
    sa.Column('nota_d4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posts')
    op.drop_table('follow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('perfis')
    # ### end Alembic commands ###
